name: Build and Publish ESPHome firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-workflow-passing-data:
    uses: ziermmar/esphome-epaper-dashboard/.github/workflows/build.yml@main
    with:
      files: dashboard-epaper.yaml
    secrets: inherit
    permissions:
      contents: write
