name: Build and Publish ESPHome firmware

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    uses: ziermmar/esphome-epaper-dashboard/.github/workflows/build.yml@main
    with:
      files: dashboard-epaper.yaml
      release-version: ${{ startsWith(github.ref, 'refs/tags/v') && github.ref_name || '' }}
      publish-pages: ${{ github.event_name == 'push' }}
      create-release: ${{ startsWith(github.ref, 'refs/tags/v') }}
    secrets: inherit
    permissions:
      contents: write
